CREATE OR REPLACE SEQUENCE SOURCE_LANGUAGES_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE SEQUENCE USER_REQUEST_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE SEQUENCE USER_REQUEST_DETAILS_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE SEQUENCE ANALYSIS_DETAILS_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE SEQUENCE DOCUMENTATION_DETAILS_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE SEQUENCE CONVERSION_DETAILS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TABLE SOURCE_LANGUAGES (
    LANGUAGE_ID NUMERIC PRIMARY KEY,
    CODE	VARCHAR,
    UPDATED_BY	NUMERIC,
    CODE_TYPE VARCHAR,
    UPDATED_BY	NUMERIC,
    UPDATED_DATETIME DEFAULT SYSDATE
);

CREATE OR REPLACE TABLE USER_REQUEST (  
    USER_REQUEST_ID NUMERIC(50) FOREIGN PRIMARY KEY,    
    ZIP_FILE_NAME VARCHAR2(255),
    ZIP_FILE_CONTENT BLOB,
    GENERATED_BRD_CONTENT BLOB,
    SOURCE_LANG_ID	NUMERIC,
    TARGET_LANG_ID	NUMERIC,
    ADDITIONAL_CONTEXT VARCHAR2(1000),
    UPDATED_BY	NUMERIC,
    UPDATED_DATETIME DEFAULT SYSDATE
);

CREATE OR REPLACE TABLE USER_REQUEST_DETAILS (
    USER_REQUEST_DETAILS_ID NUMERIC(50),
    USER_REQUEST_ID NUMERIC(50),
    FILE_NAME VARCHAR2(255),
    FILE_CONTENT CLOB,
    FILE_TYPE VARCHAR2(255),
    UPDATED_BY	NUMERIC,
    UPDATED_DATETIME DEFAULT SYSDATE,   
    FOREIGN KEY (USER_REQUEST_ID) REFERENCES USER_REQUEST(USER_REQUEST_ID),
    FOREIGN KEY (USER_REQUEST_DETAILS_ID) REFERENCES USER_REQUEST(USER_REQUEST_ID)
);

CREATE OR REPLACE TABLE ANALYSIS_DETAILS (
    ANALYSIS_DETAILS_ID NUMERIC,
    USER_REQUEST_DETAILS_ID NUMERIC,
    USER_REQUEST_ID NUMERIC,
    PACKAGE_NAME VARCHAR, 
    NUM_LINES NUMERIC, 
    NUM_LINES_NO_DOCS	NUMERIC, 
    TOKEN_COUNT	NUMERIC
    TOKEN_COUNT_NO_DOCS	NUMERIC,
    SUCCESS_FLAG BOOLEAN,
    ERROR_DETAILS VARCHAR2(1000),
    UPDATED_BY	NUMERIC,
    UPDATED_DATETIME DEFAULT SYSDATE,
    FOREIGN KEY (USER_REQUEST_ID) REFERENCES USER_REQUEST(USER_REQUEST_ID),
    FOREIGN KEY (ANALYSIS_DETAILS_ID) REFERENCES USER_REQUEST_DETAILS(USER_REQUEST_DETAILS_ID)
);

CREATE OR REPLACE TABLE DOCUMENTATION_DETAILS (
    DOCUMENTATION_DETAILS_ID NUMERIC,
    USER_REQUEST_DETAILS_ID NUMERIC,
    USER_REQUEST_ID NUMERIC,
    DOCUMENTATION_FILE_NAME VARCHAR2(255),
    DOCUMENTATION_FILE_CONTENT CLOB,
    SUCCESS_FLAG BOOLEAN,
    ERROR_DETAILS VARCHAR2(1000),
    UPDATED_BY	NUMERIC,
    UPDATED_DATETIME DEFAULT SYSDATE,
    FOREIGN KEY (USER_REQUEST_ID) REFERENCES USER_REQUEST(USER_REQUEST_ID),
    FOREIGN KEY (USER_REQUEST_DETAILS) REFERENCES USER_REQUEST_DETAILS(USER_REQUEST_DETAILS_ID)
);

CREATE OR REPLACE TABLE CONVERSION_DETAILS (
    CONVERSION_DETAILS_ID NUMERIC,
    USER_REQUEST_DETAILS_ID NUMERIC,
    USER_REQUEST_ID NUMERIC,
    CONVERSION_FILE_NAME VARCHAR2(255),
    CONVERSION_FILE_CONTENT CLOB,
    SUCCESS_FLAG BOOLEAN,
    ERROR_DETAILS VARCHAR2(1000),
    UPDATED_BY	NUMERIC,
    UPDATED_DATETIME DEFAULT SYSDATE,
    FOREIGN KEY (USER_REQUEST_ID) REFERENCES USER_REQUEST(USER_REQUEST_ID),
    FOREIGN KEY (USER_REQUEST_DETAILS) REFERENCES USER_REQUEST_DETAILS(USER_REQUEST_DETAILS_ID)
);
