CREATE SEQUENCE CODE_DOCUMENTATION_EMBEDDING_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER trg_CODE_DOCUMENTATION_EMBEDDING_pk
BEFORE INSERT ON CODE_DOCUMENTATION_EMBEDDING
FOR EACH ROW
BEGIN
    SELECT CODE_DOCUMENTATION_EMBEDDING_SEQ.NEXTVAL INTO :NEW.CODE_DOCUMENTATION_EMBEDDING_ID FROM dual;
END;
CREATE TABLE CODE_DOCUMENTATION_EMBEDDING (
    CODE_DOCUMENTATION_EMBEDDING_ID NUMBER PRIMARY KEY,
    DOCUMENTATION_DETAILS_ID NUMBER,
    USER_REQUEST_ID NUMBER,
    CODE_FILE_NAME VARCHAR2(255),
    CODE_FILE_CONTENT CLOB,
    DOCUMENTATION_FILE_NAME VARCHAR2(255),
    DOCUMENTATION_FILE_CONTENT CLOB,
    UPDATED_BY VARCHAR2(255),
    UPDATED_DATETIME DATE DEFAULT SYSDATE
);
